name: 'AWS - Dev - Terraform Test'

on:      
  push:
    branches: [ "feature/*" ]

  pull_request:
    branches: [ "feature/*" ]
  

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

jobs:
  aws-terraform-plan:
    name: 'Setup and Plan Terraform - aws - dev'
    uses: ./.github/workflows/terraform-plan-and-test.yaml
    with:
      action: plan
      environment: dev
      aws_region: eu-west-2