name: Terraform

on:
  workflow_call:
    inputs:
      stack:
        required: false
        type: string
        default: 'aws'
        description: 'The stack name for the Terraform execution.'
      environment:
        required: true
        type: string
        description: 'The environment for the Terraform execution, e.g., "dev", "staging", "prod".'
      aws_region:
        required: false
        type: string
        default: 'eu-west-2'
        description: 'The AWS region to configure credentials for.'
      role:
        required: false
        type: string
        default: 'arn:aws:iam::299858989921:role/github-actions-oidc-role'
        description: 'The AWS IAM role to assume for the GitHub Actions workflow.'
      state_bucket_prefix:
        required: false
        type: string
        default: 's3-tf-eks-helm-automation-state'
        description: 'The prefix for the S3 bucket used for Terraform state.'

jobs:
  test:
    name: 'Terraform Plan and Test - ${{ inputs.stack }} - ${{ inputs.environment }}'
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/${{ inputs.stack }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: latest

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ inputs.aws_region }}
          role-to-assume: ${{ inputs.role }}
          role-session-name: GitHubActionsSessionTest

      - name: Init
        run: terraform init -input=false

      - name: Workspace
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      - name: Format
        run: terraform fmt -check --recursive || echo "::warning file=terraform-aws::Terraform format check failed"

      - name: Validate
        run: terraform validate || echo "::warning file=terraform-aws::Terraform validation failed"

      - name: Plan
        run: |
          mkdir plan tests
          terraform plan \
            -out=plan/tfplan \
            -input=false \
            -var-file=environments/${{ inputs.environment }}.tfvars
          terraform show -json plan/tfplan > plan/plan.json

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest

      - name: Run TFLint
        run: |
          config_file="${{ github.workspace }}/.github/workflows/resources/.tflint.hcl"
          tflint --init --config "$config_file"
          tflint \
            --var-file=environments/${{ inputs.environment }}.tfvars \
            --config "$config_file" \
            --format junit > tests/tflint.xml || echo "::warning file=terraform-aws::TFLint failed"

      - name: Install and run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          skip_check: CKV_AWS_338,CKV_AWS_352,CKV_AWS_39,CKV2_AWS_19,CKV_AWS_231
          file: ${{ github.workspace }}/${{ inputs.stack }}/plan/plan.json
          output_format: junitxml
          output_file_path: ${{ github.workspace }}/${{ inputs.stack }}/tests/
          soft_fail: true

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: |
            ${{ github.workspace }}/${{ inputs.stack }}/tests/results_junitxml.xml
            ${{ github.workspace }}/${{ inputs.stack }}/tests/tflint.xml

      - name: Upload Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: ${{ github.workspace }}/${{ inputs.stack }}/plan/*
          if-no-files-found: error
